jwt:
  secret: ptbackend
server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 7702
    url: jdbc:mysql://localhost:3306/pt
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        hbm2ddl:
          auto: update
    show-sql: true
